### ISSUE TITLE
Function reminders not working as expected

### ISSUE THREAD

**Issue by KedrianLoh** [KedrianLoh/pe#4]
![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/18015a24-5951-4541-826d-be31b85b1220.png)

Created an entire list previously as seen in the screenshot. When the program is re-run, the reminder function does not work as expected. Output has incorrect name and completely wrong deadline.

**Comment by nus-pe-script** [comment]
# Team's Response
It is unclear what output the tester obtained, or how the tester obtained the output with incorrect name and completely wrong deadline.
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.IssueUnclear`]

- [x] I disagree

**Reason for disagreement:** ![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/9cdc3b4d-ad6d-4ab5-a215-044b1901ea3f.png)
This is a screenshot from the team's user guide regarding the reminders.
![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/b705242a-6894-44f4-84b1-71b13b98ee8e.png)
This is a screenshot from this post with arrows to indicate where the error lies.
Following the UG on the expected output, the output displayed in the screenshot in this post is incorrect and is hence a bug.




<catcher-end-of-segment><hr>
