### ISSUE TITLE
Error message does not match the error

### ISSUE THREAD

**Issue by KedrianLoh** [KedrianLoh/pe#6]
![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/7f56c926-7c72-4e70-91e0-a702461ec9b3.png)

Created a list as seen in the screenshot and entered command "delete c/a e1".

**Comment by nus-pe-script** [comment]
# Team's Response
The correct format for the delete command is "delete c/&lt;category name&gt; [(optional) e/&lt;event index&gt;]". In your input, there is no "e/", hence "a e1" will be taken as the category name. Therefore, the command is working as expected
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

<catcher-end-of-segment><hr>
